/*
 * generated by Xtext
 */
package org.cloudsmith.geppetto.pp.dsl.ui.internal;

import java.util.Collections;
import java.util.Map;

import org.apache.log4j.Logger;
import org.cloudsmith.geppetto.forge.ForgeService;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.shared.SharedStateModule;
import org.eclipse.xtext.util.Modules2;
import org.osgi.framework.BundleContext;

import com.google.common.collect.Maps;
import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Module;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass.
 */
public class PPActivator extends AbstractUIPlugin {

	public static final String ORG_CLOUDSMITH_GEPPETTO_PP_DSL_PP = "org.cloudsmith.geppetto.pp.dsl.PP";

	private static final Logger logger = Logger.getLogger(PPActivator.class);

	private static PPActivator INSTANCE;

	public static PPActivator getInstance() {
		return INSTANCE;
	}

	private Map<String, Injector> injectors = Collections.synchronizedMap(Maps.<String, Injector> newHashMapWithExpectedSize(1));

	protected Injector createInjector(String language) {
		try {
			Module runtimeModule = getRuntimeModule(language);
			Module sharedStateModule = getSharedStateModule();
			Module uiModule = getUiModule(language);
			Module forgeModule = getForgeModule();
			Module mergedModule = Modules2.mixin(runtimeModule, sharedStateModule, uiModule, forgeModule);
			return Guice.createInjector(mergedModule);
		}
		catch(Exception e) {
			logger.error("Failed to create injector for " + language);
			logger.error(e.getMessage(), e);
			throw new RuntimeException("Failed to create injector for " + language, e);
		}
	}

	protected Module getForgeModule() {
		return ForgeService.getDefault().getForgeModule();
	}

	public Injector getInjector(String language) {
		synchronized(injectors) {
			Injector injector = injectors.get(language);
			if(injector == null) {
				injectors.put(language, injector = createInjector(language));
			}
			return injector;
		}
	}

	protected Module getRuntimeModule(String grammar) {
		if(ORG_CLOUDSMITH_GEPPETTO_PP_DSL_PP.equals(grammar)) {
			return new org.cloudsmith.geppetto.pp.dsl.PPRuntimeModule();
		}

		throw new IllegalArgumentException(grammar);
	}

	protected Module getSharedStateModule() {
		return new SharedStateModule();
	}

	protected Module getUiModule(String grammar) {
		if(ORG_CLOUDSMITH_GEPPETTO_PP_DSL_PP.equals(grammar)) {
			return new org.cloudsmith.geppetto.pp.dsl.ui.PPUiModule(this);
		}

		throw new IllegalArgumentException(grammar);
	}

	@Override
	public void start(BundleContext context) throws Exception {
		super.start(context);
		INSTANCE = this;
	}

	@Override
	public void stop(BundleContext context) throws Exception {
		injectors.clear();
		INSTANCE = null;
		super.stop(context);
	}

}
