/*
 * generated by Xtext
 */
package org.cloudsmith.geppetto.pp.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PPExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.cloudsmith.geppetto.pp.dsl.ui.internal.PPActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.cloudsmith.geppetto.pp.dsl.ui.internal.PPActivator.getInstance().getInjector("org.cloudsmith.geppetto.pp.dsl.PP");
	}
	
}
