/*
 * generated by Xtext
 */
package org.cloudsmith.geppetto.pp.dsl.formatting;

import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#formatting
 * on how and when to use it
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
public class PPFormatter extends AbstractDeclarativeFormatter {

	@Override
	protected void configureFormatting(FormattingConfig c) {
		// THIS IS NOT USED WITH THE DOM BASED FORMATTER
		// THE GENERATOR INSIST ON CREATING THIS CLASS IF IT DOES NOT EXIST.
	}
}
