<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="forge"
    nsURI="http://www.cloudsmith.org/geppetto/1.0.0/Forge" nsPrefix="forge">
  <eClassifiers xsi:type="ecore:EClass" name="Forge">
    <eOperations name="build" eType="#//Metadata" eExceptions="#//IOException #//IncompleteException">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Build a module for release. The end result is a gzipped tar file (.tar.gz) archive that&#xD;&#xA;contains the module source and a freshly generated metadata.json. This method&#xD;&#xA;will replace the metadata.json that resides at the root of the module source&#xD;&#xA;if it is already present."/>
      </eAnnotations>
      <eParameters name="moduleSource" eType="#//File">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The module directory"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="destination" eType="#//File">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The directory where the created archive will end up. Created if necessary."/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="changes" eExceptions="#//IOException">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List modified files in an installed module"/>
      </eAnnotations>
      <eGenericType eClassifier="#//List">
        <eTypeArguments eClassifier="#//File"/>
      </eGenericType>
      <eParameters name="path" eType="#//File">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The module directory"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="generate" eExceptions="#//IOException">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Generate boilerplate for a new module"/>
      </eAnnotations>
      <eParameters name="destination" eType="#//File">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The module directory"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="metadata" eType="#//Metadata">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The name of the module"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="install" eType="#//Metadata" eExceptions="#//IOException">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Install a module (eg, 'user-modname') from a repository or file. A&#xA;module is an archive that contains one single folder. In some cases,&#xA;like when installing into a pre-existing workspace project, it's&#xA;desirable to skip this folder and instead expand everything beneath&#xA;it into the given &lt;code>destination&lt;/code>. This behavior can be&#xA;enforced by setting the &lt;code>destinationIncludesTopFolder&lt;/code>&#xA;to &lt;code>true&lt;/code>."/>
      </eAnnotations>
      <eParameters name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The name of the module"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="destination" eType="#//File">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The destination for the install."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="destinationIncludesTopFolder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="When &lt;code>true&lt;/code>, assume that all content beneath the&#xA;top folder in the archive should be installed directly beneath the&#xA;given &lt;code>destination&lt;/code>. When this flag is &lt;code>false&#xA;&lt;/code>, the top folder of the archive will be expanded as-is&#xA;beneath the &lt;code>destination&lt;/code>.&#xA;"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="force" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Set to &lt;code>true&lt;/code> to overwrite an existing module."/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="search" eExceptions="#//IOException">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Search the module repository for a module matching &lt;code>term&lt;/code>"/>
      </eAnnotations>
      <eGenericType eClassifier="#//List">
        <eTypeArguments eClassifier="#//ModuleInfo"/>
      </eGenericType>
      <eParameters name="term" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Search term"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="getRelease" eType="#//ReleaseInfo" eExceptions="#//IOException">
      <eParameters name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The version of the repository service"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repository" lowerBound="1"
        eType="#//Repository" changeable="false" transient="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cache" lowerBound="1" eType="#//Cache"
        changeable="false" transient="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" lowerBound="1"
        eType="#//ForgeService" changeable="false" transient="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForgeService">
    <eOperations name="createCache" eType="#//Cache">
      <eParameters name="cacheDirectory" eType="#//File">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The local cache directory"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="repository" eType="#//Repository">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The remote repository"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="createForge" eType="#//Forge">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Creates an instance that lets you create, publish, and consume modules."/>
      </eAnnotations>
      <eParameters name="repository" eType="#//URI">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The location of the repository"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="createForge" eType="#//Forge">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Obtain a service instance that gives you access to the module repository at the given location."/>
      </eAnnotations>
      <eParameters name="repository" eType="#//URI">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The location of the repository"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="cacheDirectory" eType="#//File">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The local cache directory"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="createForge" eType="#//Forge">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Obtain a service instance that gives you access to the module repository at the given location."/>
      </eAnnotations>
      <eParameters name="repository" eType="#//Repository">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The remote repository"/>
        </eAnnotations>
      </eParameters>
      <eParameters name="cache" eType="#//Cache">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The local cache"/>
        </eAnnotations>
      </eParameters>
    </eOperations>
    <eOperations name="createMetadata" eType="#//Metadata">
      <eParameters name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="createRepository" eType="#//Repository">
      <eParameters name="uri" eType="#//URI"/>
    </eOperations>
    <eOperations name="loadJSONMetadata" eType="#//Metadata" eExceptions="#//IOException">
      <eParameters name="jsonFile" eType="#//File"/>
    </eOperations>
    <eOperations name="loadModule" eType="#//Metadata" eExceptions="#//IOException">
      <eParameters name="moduleDirectory" eType="#//File"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The full name of the module"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The short name (id) for the module"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectURL" eType="#//URI">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The location of the module"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cache">
    <eOperations name="retrieve" lowerBound="1" eType="#//File" eExceptions="#//IOException">
      <eParameters name="fileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="clean" eExceptions="#//IOException"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="#//File"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repository" lowerBound="1"
        eType="#//Repository" changeable="false" transient="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repository">
    <eOperations name="connect" eType="#//HttpURLConnection" eExceptions="#//IOException">
      <eParameters name="method" eType="#//HttpMethod"/>
      <eParameters name="urlSuffix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repository" lowerBound="1"
        eType="#//URI" changeable="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The repository location"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cacheKey" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReleaseInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="file" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Metadata">
    <eOperations name="loadModuleFile" eExceptions="#//IOException">
      <eParameters name="moduleFile" eType="#//File"/>
    </eOperations>
    <eOperations name="loadTypeFiles" eExceptions="#//IOException">
      <eParameters name="puppetDir" eType="#//File"/>
    </eOperations>
    <eOperations name="loadChecksums" eExceptions="#//IOException">
      <eParameters name="moduleDir" eType="#//File"/>
    </eOperations>
    <eOperations name="saveJSONMetadata" eExceptions="#//IOException">
      <eParameters name="jsonFile" eType="#//File"/>
    </eOperations>
    <eOperations name="saveModulefile" eExceptions="#//IOException">
      <eParameters name="moduleFile" eType="#//File"/>
    </eOperations>
    <eOperations name="parseVersionRequirement" eType="#//VersionRequirement">
      <eParameters name="versionRequirement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="user" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" volatile="true"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="#//File"
        changeable="false" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="license" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="summary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectPage" eType="#//URI"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checksums" changeable="false">
      <eGenericType eClassifier="#//Map">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eTypeArguments eClassifier="#//byteArray"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
        eType="#//Dependency" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dependency">
    <eOperations name="matches" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repository" eType="#//URI"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versionRequirement" eType="#//VersionRequirement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" eSuperTypes="#//Documented">
    <eOperations name="loadTypeFile" eExceptions="#//IOException">
      <eParameters name="typeFile" eType="#//File"/>
    </eOperations>
    <eOperations name="loadProvider" eExceptions="#//IOException">
      <eParameters name="providerDir" eType="#//File"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providers" upperBound="-1"
        eType="#//Provider" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//Documented"/>
  <eClassifiers xsi:type="ecore:EClass" name="Documented" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//Documented"/>
  <eClassifiers xsi:type="ecore:EClass" name="Provider" eSuperTypes="#//Documented"/>
  <eClassifiers xsi:type="ecore:EClass" name="VersionRequirement">
    <eOperations name="matches" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="version" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="findBestMatch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="versions" lowerBound="1">
        <eGenericType eClassifier="#//Iterable">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="matchRule" lowerBound="1"
        eType="#//MatchRule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MatchRule">
    <eLiterals name="PERFECT" literal="==">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Version must match exactly the specified version."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="EQUIVALENT" value="1" literal="=">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Version must be at least at the version specified, or at a higher service level (major and minor version levels must equal the specified version)."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="COMPATIBLE" value="2" literal="~">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Version must be at least at the version specified, or at a higher service level or minor level (major version level must equal the specified version)."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="LESS" value="3" literal="&lt;">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Version must be less than the version specified."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="LESS_OR_EQUAL" value="4" literal="&lt;=">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Version must be at less or equal ot the version specified."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="GREATER" value="5" literal=">">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Version must be greater than the version specified."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="GREATER_OR_EQUAL" value="6" literal=">=">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Version must be greater or equal to the version specified."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="byteArray" instanceClassName="byte[]"/>
  <eClassifiers xsi:type="ecore:EDataType" name="File" instanceClassName="java.io.File"/>
  <eClassifiers xsi:type="ecore:EEnum" name="HttpMethod">
    <eLiterals name="GET"/>
    <eLiterals name="HEAD" value="1"/>
    <eLiterals name="PUT" value="2"/>
    <eLiterals name="POST" value="3"/>
    <eLiterals name="DELETE" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="HttpURLConnection" instanceClassName="java.net.HttpURLConnection"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IllegalArgumentException" instanceClassName="java.lang.IllegalArgumentException"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IncompleteException" instanceClassName="org.cloudsmith.geppetto.forge.IncompleteException"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IOException" instanceClassName="java.io.IOException"/>
  <eClassifiers xsi:type="ecore:EDataType" name="List" instanceClassName="java.util.List">
    <eTypeParameters name="E"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Map" instanceClassName="java.util.Map">
    <eTypeParameters name="K"/>
    <eTypeParameters name="V"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="StringArray" instanceClassName="java.lang.String[]"/>
  <eClassifiers xsi:type="ecore:EDataType" name="URI" instanceClassName="java.net.URI"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Iterable" instanceClassName="java.util.Iterable">
    <eTypeParameters name="E"/>
  </eClassifiers>
</ecore:EPackage>
