/*
* generated by Xtext
*/
package org.cloudsmith.geppetto.pp.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PPAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/cloudsmith/geppetto/pp/dsl/parser/antlr/internal/InternalPPParser.tokens");
	}
}
