#!/bin/bash
#
[ -n "$PID_FILE" ] || {
	echo "No server appears to be running" 1>&2
	exit 1
}
SERVER_PID="`cat "$PID_FILE"`" || {
	echo "Failed to read pid file '$PID_FILE'" 1>&2
	exit 2
}
kill "$SERVER_PID" || {
	echo "Failed to kill the server" 1>&2
}
exit 0
